#!/bin/bash
# Warn before pushing to protected branches
# Make script executable with chmod +x pre-push
# Bypass with git push --no-verify

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(master|dev|release-*|patch-*)"

read -p "Cat you are about to push to \"$BRANCH\" (Y/n): " -n 1 -r < /dev/tty
echo
if [[ $REPLY =~ ^[nN]$ ]]; then
    exit 1
else
    exit 0
fi
echo "Push aborted."
exit 1
